apps:
  - id: "com.finaccel.android"
    name: "kredivo"
  - id: "id.co.shopintar"
    name: "atome"
  - id: "io.silvrr.installment"
    name: "akulaku"
  - id: "id.co.bri.ceria"
    name: "ceria"
    
scraping:
  sleep_milliseconds: 30
  language: "id"
  country: "id"
  sort: "newest"

topic_modeling:
  input_file: "data/raw/ceria_reviews.csv"
  num_topics: 5

oversampling:
  ceria: "data/raw/ceria_reviews.csv"
  kredivo: "data/raw/kredivo_reviews.csv"
  atome: "data/raw/atome_reviews.csv"
  akulaku: "data/raw/akulaku_reviews.csv"
  